
interface LandingFeaturesProps {}

const LandingFeatures = ({}: LandingFeaturesProps) => {
  const features = [
    {
      icon: "🔍",
      title: "AI-Powered Discovery",
      description: "Find the perfect influencers for your brand using advanced AI algorithms that match creators to your specific niche and audience."
    },
    {
      icon: "🤖",
      title: "Automated Outreach",
      description: "Scale your outreach with personalized messages generated by AI, saving hours while maintaining authentic communication."
    },
    {
      icon: "📊",
      title: "Performance Analytics",
      description: "Track campaign performance in real-time with detailed analytics and insights to optimize your influencer marketing ROI."
    },
    {
      icon: "💰",
      title: "Secure Payments",
      description: "Handle all payments securely through our platform with milestone-based releases and automated invoice generation."
    },
    {
      icon: "📋",
      title: "Contract Management",
      description: "Generate and manage contracts automatically with legal compliance built-in for hassle-free partnerships."
    },
    {
      icon: "🎯",
      title: "Campaign Optimization",
      description: "Optimize your campaigns with AI-driven insights and recommendations to maximize engagement and conversions."
    }
  ];

  return (
    <section id="features" className="py-16 px-4 sm:px-6 lg:px-8 bg-white">
      <div className="max-w-6xl mx-auto">
        {/* Section header */}
        <div className="text-center mb-12">
          <div className="inline-flex items-center px-3 py-1 rounded-full bg-blue-100 text-blue-700 text-sm font-medium mb-4">
            ⚡ Platform Features
          </div>
          <h2 className="text-3xl sm:text-4xl font-bold text-gray-900 mb-4">
            Everything you need to scale influencer marketing
          </h2>
          <p className="text-lg text-gray-600 max-w-2xl mx-auto">
            From discovery to payment — our AI-powered platform automates your entire influencer workflow.
          </p>
        </div>
        
        {/* Features grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {features.map((feature, index) => (
            <div key={index} className="p-6 rounded-xl bg-gray-50 hover:bg-white hover:shadow-lg transition-all duration-300 border border-gray-100">
              <div className="text-3xl mb-4">{feature.icon}</div>
              <h3 className="text-xl font-semibold text-gray-900 mb-3">{feature.title}</h3>
              <p className="text-gray-600 leading-relaxed">{feature.description}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default LandingFeatures;
